### ISSUE TITLE
GUID collection unmarshal is broken for models/api_application

### ISSUE THREAD

**Issue by jjwedemyer** [microsoftgraph/msgraph-sdk-go#412] opened 2023-02-27 13:50 UTC
Hi,

I have found an issue with the unmarshal for the GUID collections in api_application model. It will fail consistently on applications where `knownClientApplications` is not empty, but will not fail on applications where `knownClientApplications` is empty
The issue seems to be with the parameter in [api_application.go#L58](https://github.com/microsoftgraph/msgraph-sdk-go/blame/7d431b39ae4fe0496fcf866aa32a20034b08763b/models/api_application.go#L58):
` val, err := n.GetCollectionOfPrimitiveValues("i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID")`

This then will fail in the kiota json parser: [kiota-serialization-json-go/json_parse_node.go:L277-L310](https://github.com/microsoft/kiota-serialization-json-go/blob/870d4ed9c672539ce6e0abf01a74b8e5a5396263/json_parse_node.go#L277-L310)

**Comment by baywet** [comment] 2023-02-27 14:24
Thanks for reporting this.
Is this something you'd be willing to submit a PR for?


Here 
https://github.com/microsoft/kiota/blob/37a1b9014dee20c1cfa34a754b8ace869296de47/src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs#L866

There should be a third false

And this could be updated to have the third false as well and do away with the splitting etc.

https://github.com/microsoft/kiota/blob/37a1b9014dee20c1cfa34a754b8ace869296de47/src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs#LL927C23-L927C23

**Comment by jjwedemyer** [comment] 2023-02-28 10:18
Sure.
I'll try to fix this and submit a PR to that Repo.

**Comment by djuneja-uptycs** [comment] 2023-03-02 05:02
@jjwedemyer @baywet 
Is this fixed? I see the PR is merged but I am not able to get a new build. Any update on this?

**Comment by baywet** [comment] 2023-03-02 13:06
The issue is fixed in the generator, we still need to generate an publish an update to the SDK.  We're hoping that's going to happen by the end of this week or early next. We'll update this issue when it's done.

**Comment by baywet** [comment] 2023-03-03 13:09
Fixed by #422, v0.56.0

**Closed by baywet** 2023-03-03 13:09 UTC
Labels: bug
