### ISSUE TITLE
Detailed error messages from API calls

### ISSUE THREAD

**Issue by mebert1** [microsoftgraph/msgraph-sdk-go#510] opened 2023-06-08 20:52 UTC
Is there a plan to improve the error response when sending a request via the MS Graph Service Client?

Currently, the only error message returned is

     error status code received from the API

no matter what the issue with the request is. Our team has come across multiple scenarios in which it'd be helpful to receive more insight into the error cause. Only to name a few, that could be:
 
* Incorrectly formatted query parameters
* Expired access codes - unauthorized
* Missing scopes
* The requested resource does not exist (Microsoft account without mail service)
* ...

Not only would more detailed error messages or returned error codes improve debugging capabilities, but it could also tremendously improve user interactions for any product that is dependent on this SDK.

Would appreciate any insight on whether this is in the works or already exists and I am simply missing something.

Thanks,
Marius

**Comment by zdevaty** [comment] 2023-06-12 09:25
This was addressed a bit in #214, so you can take some inspiration from there.

But I ran into this issue now as well, and I think there should at least be better documentation on error handling. I went through the examples on learn.microsoft.com and found no mention of error handling in the Go SDK.

**Comment by zdevaty** [comment] 2023-06-12 12:59
I have seen that example, it comes from the issue I linked. But for me as a newcomer is difficult to understand what `odataerrors.ODataError` is, and what other types of errors could be returned.

**Comment by jake-billings** [comment] 2023-06-12 21:14
+1 I just hit this issue, and this seems like a really lame way to handle errors. Why not just move the contents of printOdataError to the implementation of `Error()`, so that people can read the error messages?

**Comment by baywet** [comment] 2023-06-13 13:01
For context here this code is generated and not manually written. The challenges of "generating the error method" are the following:
- The fields, or even the fact the error is a structured type varies depending on APIs (other APIs than Microsoft Graph)
- There's no information in the OpenAPI description that conveys "this is what you should use for the error method implementation" to the generator.
- Even if the errors were standardized across APIs, and the information to use for the error implementation was conveyed by the API description, we'd be carrying forward an API owner opinion to the client side. Your scenario might care about other aspects.

For all those reasons, we chose to give the choice to the SDK/client user and provide detailed information on how you get to that information so you can implement things however you desire.

Does this make sense?

**Comment by jake-billings** [comment] 2023-06-15 02:36
Actually, no, this does not make sense.

Anyone using this SDK is going to have a poor experience here if we chose not to include error messages in the .Error() function of our error.

The added documentation helps, but it doesn't include most of the information in the error object - it misses innerError, error details, additionalData etc..

Are we expecting callers of the library to read the generated source to write their own functions to dig up the status code and error details?

**Comment by baywet** [comment] 2023-06-15 12:25
This is fair feedback.
No we don't expect customers to inspect the sources. However we provide documentation (granted documentation is not always read, and can always be improved) to answer those kind of questions.

But let's take Microsoft Graph as an example, what information would you like to see in the Error() return? how should it be structured?

**Comment by jake-billings** [comment] 2023-06-15 16:15
Like any error message, it should contain an actionable string such that a developer could identify and fix the cause of an error.

I think the absolute minimum here would be the http status code and error message returned from graph. That way a user could see something like "500 Server Error" or "400 Bad Request: invalid field \'theInvalidField\' should be a string".

My use case emits logs to a logging service for a web service, so we want all the information we can possibly get as we will be debugging the errors well after they occur.

Here's the function I wrote based on the docs and after inspecting the source:

```
func formatErrorIfOData(err error) error {
	if err == nil {
		return nil
	}

	builder := strings.Builder{}

	var typed *odataerrors.ODataError
	if errors.As(err, &typed) {
		builder.WriteString(fmt.Sprintf("error: %s", typed.Error()))

		builder.WriteString(fmt.Sprintf(" status code: %d", typed.ApiError.ResponseStatusCode))

		if backingStore := typed.GetBackingStore(); backingStore != nil {
			backingStoreMap := backingStore.Enumerate()

			builder.WriteString(" backing store: ")

			marshaledBackingStoreMap, err := json.Marshal(backingStoreMap)
			if err != nil {
				builder.WriteString("error occurred when marshaling backing store map")
			} else {
				builder.Write(marshaledBackingStoreMap)

			}
		}

		if mainErrorable := typed.GetError(); mainErrorable != nil {
			if errorCode := mainErrorable.GetCode(); errorCode != nil {
				builder.WriteString(fmt.Sprintf(" code: %s", *errorCode))
			}
			if message := mainErrorable.GetMessage(); message != nil {
				builder.WriteString(fmt.Sprintf(" message: %s", *message))
			}
			if target := mainErrorable.GetTarget(); target != nil {
				builder.WriteString(fmt.Sprintf(" target: %s", *target))
			}
			if details := mainErrorable.GetDetails(); details != nil {
				for detailIndex, detail := range details {
					builder.WriteString(fmt.Sprintf(" detail %d: ", detailIndex))
					if errorCode := detail.GetCode(); errorCode != nil {
						builder.WriteString(fmt.Sprintf(" detail %d code: %s", detailIndex, *errorCode))
					}
					if message := detail.GetMessage(); message != nil {
						builder.WriteString(fmt.Sprintf(" detail %d code: %s", detailIndex, *message))
					}
					if target := detail.GetTarget(); target != nil {
						builder.WriteString(fmt.Sprintf(" detail %d code: %s", detailIndex, *target))
					}
				}
			}
			if innerError := mainErrorable.GetInnererror(); innerError != nil {
				if clientRequestId := innerError.GetClientRequestId(); clientRequestId != nil {
					builder.WriteString(fmt.Sprintf(" inner error client request id: %s", *clientRequestId))
				}
				if date := innerError.GetDate(); date != nil {
					builder.WriteString(fmt.Sprintf(" inner error date: %s", *date))
				}
				if oDataType := innerError.GetOdataType(); oDataType != nil {
					builder.WriteString(fmt.Sprintf(" inner error odata type: %s", *oDataType))
				}
				if requestId := innerError.GetRequestId(); requestId != nil {
					builder.WriteString(fmt.Sprintf(" inner error odata type: %s", *requestId))
				}
			}
		}

		if additionalData := typed.GetAdditionalData(); additionalData != nil {
			builder.WriteString(" additional data: ")

			marshaledAdditionalData, err := json.Marshal(additionalData)
			if err != nil {
				builder.WriteString("error occurred when marshaling additional data map")
			} else {
				builder.Write(marshaledAdditionalData)

			}
		}
	} else {
		builder.WriteString(err.Error())
	}

	return fmt.Errorf("%s", builder.String())
}
 ```

**Comment by pandeyabs** [comment] 2023-07-20 22:23
> I think the absolute minimum here would be the http status code and error message returned from graph.".

Thanks @jake-billings for this. As a graph SDK consumer, having Error() return above^ will make our lives so much easier. 

In absence of that, we have to rely on odata error messages from graph, which are not consistent & keep changing. For example, we have seen 3 different kind of odata error messages from graph when we try to [get a user's drive](https://learn.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-1.0&tabs=http), but user doesn't have one. 
* `user's mysite not found`
* `unable to retrieve user's mysite url`
* `404 FILE NOT FOUND` - most recently seen.

Currently, we have to rely on [error string matching ](https://github.com/alcionai/corso/blob/9359679f9967b7f0eaae245d89c96f2a3727f79a/src/internal/m365/graph/errors.go#L67) for graph errors, which has several downsides.

1. Big operational burden, we have to keep patching code to adjust to new error messages from graph
2. Error messages are misleading, for e.g. `404 FILE NOT FOUND` for a missing drive doesn't make sense. End user may perceive it as a file not found error. 

Having access to underlying http status codes would be a much better alternative here. Based off @jake-billings's code snippet, it should be pretty straightforward to add to graph sdk. Could MSFT please prioritize this? :)

**Comment by baywet** [comment] 2023-07-21 12:41
Thanks for the extensive feedback on the matter.

First off, all generated error types derive from API error which [exposes the http status code](https://github.com/microsoft/kiota-abstractions-go/blob/9f9f3af8d9661fad4c165be9c7851f2b69603043/api_error.go#L8) (as well as the response headers)

The challenge in formatting the error message is those types are generated from the API description. And OpenAPI (the format of the description) doesn't have a place holder to describe "here is how you get the error content". So we'd have to rely on hard coded assumptions (not possible), have a less than indicative message (not great as your feedback outlines), or come up with an extension to carry this information in the metadata (longer process, not prioritized at this point).

Let me loop in @maisarissi (PM for this SDK) and @sebastienlevert (PM for languages experience in the generator) so they can help with prioritization.

**Comment by pandeyabs** [comment] 2023-07-21 17:55
Thanks @baywet ! Appreciate your quick response. 

> First off, all generated error types derive from API error which [exposes the http status code](https://github.com/microsoft/kiota-abstractions-go/blob/9f9f3af8d9661fad4c165be9c7851f2b69603043/api_error.go#L8) (as well as the response headers)

It should be safe for sdk consumers to source the http status from above right? I'm assuming the above code & underlying dependencies won't be changing so much. Please let me know if there are any big risks here :)

**Comment by baywet** [comment] 2023-07-21 18:22
Yes we're holding the kiota API surface to the same standard we hold the Microsoft Graph API surface : no binary breaking changes. [more details](https://learn.microsoft.com/en-us/openapi/kiota/support)

**Comment by baywet** [comment] 2023-09-13 11:32
Update: thanks everyone for your patience.
We've made progress on this and implemented error message mapping in the generator.
https://github.com/microsoft/kiota/issues/3066

You should start seeing more explicit messages from the service without having to type assert with the next release.

**Comment by baywet** [comment] 2023-09-22 20:07
Hi everyone,
Thanks for your patience on that. If you upgrade to 1.19.0 or above you'll see the main error message without having to cast the error that's being returned.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/c9ca3cd82caabb3182282e4a99fe429f297e4667/models/odataerrors/o_data_error.go#L29

Closing.

**Closed by baywet** 2023-09-22 20:07 UTC
Labels: documentation, enhancement
