### ISSUE TITLE
requestInfo.AddRequestOptions(options.Options...) (no value) used as value

### ISSUE THREAD

**Issue by jozephp** [microsoftgraph/msgraph-sdk-go#149] opened 2022-05-02 07:34 UTC
## Issue Description : 

I was using the golang v1.17.9 and to fetch user details from Graph API I was using the msgraph-sdk-go-core v0.23.0 & msgraph-sdk-go v0.20.0 last week there was an update of msgraph-sdk-go-core@v0.23.0 and later msgraph-sdk-go@v0.20.0. After these upgrades I am unable to run my code since it fails with 

```

# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/archive
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/archive/archive_request_builder.go:57:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/archive/archive_request_builder.go:57:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18
# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/count/count_request_builder.go:55:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/count/count_request_builder.go:55:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18
# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/favorite
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/favorite/favorite_request_builder.go:57:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/favorite/favorite_request_builder.go:57:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18
# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/markread
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/markread/mark_read_request_builder.go:57:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/markread/mark_read_request_builder.go:57:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18
# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/markunread
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/markunread/mark_unread_request_builder.go:57:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/markunread/mark_unread_request_builder.go:57:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18
# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/unarchive
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/unarchive/unarchive_request_builder.go:57:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/unarchive/unarchive_request_builder.go:57:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18
# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/unfavorite
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/unfavorite/unfavorite_request_builder.go:57:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/unfavorite/unfavorite_request_builder.go:57:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18
# github.com/microsoftgraph/msgraph-sdk-go/admin/serviceannouncement/messages/item/attachments/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/item/attachments/count/count_request_builder.go:55:45: invalid use of ... in call to requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/admin/serviceannouncement/messages/item/attachments/count/count_request_builder.go:55:45: requestInfo.AddRequestOptions(options.Options...) used as value
note: module requires Go 1.18

....
```

I upgraded my golang to 1.18.1 windows amd64, but the error still continues 

```
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/managedebooks/item/userstatesummary/item/devicestates/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mdmwindowsinformationprotectionpolicies/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mdmwindowsinformationprotectionpolicies/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mdmwindowsinformationprotectionpolicies/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileappcategories/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappcategories/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappcategories/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileappconfigurations/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileappconfigurations/item/assignments/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/item/assignments/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/item/assignments/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileappconfigurations/item/devicestatuses/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/item/devicestatuses/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/item/devicestatuses/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileappconfigurations/item/userstatuses/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/item/userstatuses/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileappconfigurations/item/userstatuses/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileapps/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileapps/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileapps/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileapps/item/assignments/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileapps/item/assignments/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileapps/item/assignments/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/mobileapps/item/categories/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileapps/item/categories/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/mobileapps/item/categories/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/syncmicrosoftstoreforbusinessapps
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/syncmicrosoftstoreforbusinessapps/sync_microsoft_store_for_business_apps_request_builder.go:54:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/syncmicrosoftstoreforbusinessapps/sync_microsoft_store_for_business_apps_request_builder.go:54:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/targetedmanagedappconfigurations/count
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/targetedmanagedappconfigurations/count/count_request_builder.go:55:16: cannot use ... in call to non-variadic requestInfo.AddRequestOptions
/mytemp/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.21.0/deviceappmanagement/targetedmanagedappconfigurations/count/count_request_builder.go:55:16: requestInfo.AddRequestOptions(options.Options...) (no value) used as value
# github.com/microsoftgraph/msgraph-sdk-go/deviceappmanagement/targetedmanagedappconfigurations/item/apps/count
```

Do we know how to fix this error ?

**Comment by baywet** [comment] 2022-05-02 12:42
Hey @jozephp,
Thanks for reaching out and for trying the Go SDK.
We've made several breaking changes over the last week to improve the overall user experience.
If the kiota dependencies and go core have been updated, we're still missing a new code generation (should happen tomorrow).
My guess is that you ran go get with the -u switch which updates everything to the latest version regardless of version requirements.
Two options for you at this point:
- wait for tomorrow's pull request
- revert the dependencies versions to [what's currently in the go mod file](https://github.com/microsoftgraph/msgraph-sdk-go/blob/0b6b364c2747bf9190f5b2dc2a5417ac5eaeb0c1/go.mod#L6)

For reference #146

**Comment by dadams39** [comment] 2022-05-04 20:26
I am noting similar failures for the updated versioning. Switching the go.mod back to the previous version is fine.
Command: `$ golangci-lint run`
Produces:
```
WARN [linters context] gosimple is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters context] staticcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters context] unused is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
```
This is the expected behavior.
Is there a current guide on the new requirements for adapters or is another push coming to fix these errors?

**Comment by baywet** [comment] 2022-05-05 12:21
version [0.22.0](https://github.com/microsoftgraph/msgraph-sdk-go/releases/tag/v0.22.0) was released tuesday and fixes the misalignment issues. Are you on that version?

**Comment by baywet** [comment] 2022-05-10 17:49
Thanks for the additional information here. Closing this since there was no reply from the author since the thread creation. Feel free to open a new issue if you still need help or reply here so I re-open it.

**Closed by baywet** 2022-05-10 17:49 UTC
Labels: bug, fixed, Needs author feedback
