### ISSUE TITLE
.Applications().ByApplicationIdString(appId).Get() returns 404 for App Id

### ISSUE THREAD

**Issue by jjwedemyer** [microsoftgraph/msgraph-sdk-go#569] opened 2023-09-06 17:35 UTC
Hi,
I've been trying to retrieve apps with this method: `client.Applications().ByApplicationIdString("appId").Get()`
I first tried to use the application Id as listed in the Azure Portal. That returned 404 for multiple apps.
```
 error status code received from the APIcode: Request_ResourceNotFoundmsg: Resource '<appId here>' does not exist or one of its queried reference-property objects are not present
```
I've then switched to the ObjectID of the application and that works totally fine.

I don't know if this is a bug or by design. If this is by design, consider renaming the method back to `ById()`.

**Comment by baywet** [comment] 2023-09-06 17:59
Thanks for reporting this. It's a duplicate of #508 where you'll find the details of why this edge case is confusing. Closing

**Closed by baywet** 2023-09-06 17:59 UTC
Labels: duplicate, question

**Comment by jjwedemyer** [comment] 2023-09-06 18:29
@baywet  Thank you for the link. Somehow I didn't find#508 when I searched for the problem.

Are there plans to release a method using the appId (i.e. `/applications(appId='{appId}')`) query into the SDK?

**Comment by baywet** [comment] 2023-09-07 12:23
It's already here 
https://github.com/microsoftgraph/msgraph-sdk-go/blob/061b5ce3cd5d7b3e4a5a625a593175b2bd9fc1ba/graph_base_service_client.go#L110
https://github.com/microsoftgraph/msgraph-sdk-go/blob/061b5ce3cd5d7b3e4a5a625a593175b2bd9fc1ba/applicationswithappid/applications_with_app_id_request_builder.go#L47

client.ApplicationsWithAppId("appId").Get(context.Background())

**Comment by jjwedemyer** [comment] 2023-09-07 20:09
Thank you!
