### ISSUE TITLE
value is not a collection when trying to client.DirectoryObjects().GetByIds().Post(&opts)

### ISSUE THREAD

**Issue by mblaschke** [microsoftgraph/msgraph-sdk-go#83] opened 2022-02-19 18:12 UTC
I'm trying to switch from azuread.graph (azure-sdk-for-go) to microsoft.graph but `client.DirectoryObjects().GetByIds().Post()` fails with an `value is not a collection` error.

i guess i'm doing something wrong?!
I have a list of principals IDs which i'm trying to translate with an application id (non interative user)

```
	cred, err := azidentity.NewEnvironmentCredential(nil)
	if err != nil {
		panic(err)
	}

	auth, err := a.NewAzureIdentityAuthenticationProvider(cred)
	if err != nil {
		panic(err)
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		panic(err)
	}

	client := msgraphsdk.NewGraphServiceClient(adapter)

	opts := getbyids.GetByIdsRequestBuilderPostOptions{
		Body: getbyids.NewGetByIdsRequestBody(),
	}
	opts.Body.SetIds([]string{....})

	result, err := client.DirectoryObjects().GetByIds().Post(&opts)
	if err != nil {
		panic(err)
	}
```

**Comment by baywet** [comment] 2022-02-21 13:52
Hi @mblaschke 
Thanks for trying the Go SDK and thanks for reaching out.
The issue is caused because this [generated method](https://github.com/microsoftgraph/msgraph-sdk-go/blob/f5f840510892639a99630ea61b8dcf0e5dd9db0f/directoryobjects/getbyids/get_by_ids_request_builder.go#L67) is incorrect.
This is the same exact issue pattern as #57 
We're getting closer to releasing the new version of the conversion library (see linked post) with only 2 issues left in the milestone.
I'm going to go ahead and close this issue as it's duplicate of the other one. Can you go ahead and subscribe to the other one to be notified when the fix rolls out please?

**Closed by baywet** 2022-02-21 13:52 UTC
Labels: bug, duplicate
