### ISSUE TITLE
Can't start program after integrating msgraph Macbook uses a lot of CPU

### ISSUE THREAD

**Issue by RichardLindhout** [microsoftgraph/msgraph-sdk-go#189] opened 2022-06-06 21:07 UTC
This is my code
```golang
package outlook

import (
	"fmt"

	"github.com/rs/zerolog/log"

	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	a "github.com/microsoft/kiota-authentication-azure-go"
	msgraphsdk "github.com/microsoftgraph/msgraph-beta-sdk-go"
)

type Client struct {
}

func NewClient() *Client {
	log.Info().Msg("NewClientSecretCredential")
	log.Debug().Msg("NewClientSecretCredential")

	cred, err := azidentity.NewClientSecretCredential(
		"----------",
		"---------",
		"-------",
		nil,
	)
	log.Debug().Msg("NewAzureIdentityAuthenticationProviderWithScopes")
	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"User.Read", "Calendar.Read"})
	if err != nil {
		log.Fatal().Err(err).Msg("outlook provider")
	}
	log.Debug().Msg("NewGraphRequestAdapter")
	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		log.Fatal().Err(err).Msg("outlook provider")
	}

	log.Debug().Msg("NewGraphServiceClient")
	client := msgraphsdk.NewGraphServiceClient(adapter)
	log.Debug().Msg("client.Me().Get()")
	result, err := client.Me().Get()
	if err != nil {
		log.Fatal().Err(err).Msg("outlook provider")
	}
	log.Debug().Msg("Done!")
	fmt.Println(result)
	return &Client{}
}

func (o *Client) Sync() {
	// o.c.NewSession()
}

```
I have to wait like 2 minutes before the program starts. Before it logs anything (it does nothing at all in the beginning). This is unusable a.t.m. I think it will be required to split it up in multiple packages or something

After removing NewClient() it starts in miliseconds

**Comment by RichardLindhout** [comment] 2022-06-06 21:07
<img width="311" alt="Schermafbeelding 2022-06-06 om 23 07 30" src="https://user-images.githubusercontent.com/6492229/172249451-59164a97-5104-4c8b-8ac2-aac9f35c2993.png">

**Comment by baywet** [comment] 2022-06-06 21:40
Thanks for reporting this. Duplicate of #129. Have a look at the thread and the investigations in progress. Closing.

**Closed by baywet** 2022-06-06 21:40 UTC
Labels: Needs Triage :mag:

**Comment by RichardLindhout** [comment] 2022-06-13 11:50
Want to let you know it works, I was too negative. The api is also great with the builder pattern would be great if the run time could be improved later on :)

**Comment by baywet** [comment] 2022-06-20 13:56
Thanks for the additional feedback. I'm guessing you're referring to the build time to be specific?

**Comment by RichardLindhout** [comment] 2022-06-20 21:19
yes
