### ISSUE TITLE
Sending an email returns an error regarding timestamp format.

### ISSUE THREAD

**Issue by d3v1l401** [microsoftgraph/msgraph-sdk-go#540] opened 2023-07-24 10:41 UTC
Greetings,

when sending a `models.Message` object (Email), the Azure application will result in a time format error that is not handled by my application, but from msgraph.

1. Calling my mail.Send()
![immagine](https://github.com/microsoftgraph/msgraph-sdk-go/assets/7295314/3488b0cf-7056-4fe2-a163-7b5ef0feffee)

2. Relying on msghraph APIs to perform the POST call
![immagine](https://github.com/microsoftgraph/msgraph-sdk-go/assets/7295314/d4ee8bd9-42bd-451f-bf10-4569c09aab77)

3. Resulting error
![immagine](https://github.com/microsoftgraph/msgraph-sdk-go/assets/7295314/9e28627c-bc4a-44d2-944b-9c1e00fa70a6)

I have added `sendTime` after experiencing this error, hoping it could solve the issue since I am not involving timestamps at any steps of my code that has been mostly taken from MSDN (could not find the link at the moment).

Any ideas what can I do?

**Comment by baywet** [comment] 2023-07-24 12:33
Hi @d3v1l401 
This sounds a lot like a duplicate of #527
Can you make sure your dependencies are up to date (especially the kiota json dependency) and see if you still run into the issue please?

**Closed** 2023-07-24 15:32 UTC
Labels: question, Needs author feedback
